//! A whole run as USD, so usdview, Omniverse, Houdini and Maya are the viewport.
//!
//! # Why this rung, and why now
//!
//! `ARCHITECTURE.md` recorded the decision not to compete on rendering, and named this as the next
//! step **conditional**: "a USD writer is the next rung, and only worth it if the readers really
//! are Omniverse." The condition is what made it wait, and the condition is now met.
//!
//! # What USD does that glTF cannot
//!
//! glTF animates node transforms and morph targets. A field whose values change is neither, so
//! [`gltf`](crate::gltf::gltf) exports one frame and says so. USD has **time samples on any attribute**,
//! so a run is one file: the topology is written once and the colours are written per frame, and
//! usdview's timeline scrubs the simulation rather than a camera move.
//!
//! That is the whole reason this takes `&[Frame]` where `gltf` takes one. Writing a run as a
//! sequence of glTF files would be a directory the reader has to reassemble.
//!
//! # And what it does that no picture can
//!
//! Carry the numbers. A domain with no geometry at all — a heater, a lamp, a winding, a thermal
//! network — is most of what a scene in this workspace contains, and it has no shape to draw. USD
//! is extensible, so each domain's scalars are written as **custom attributes with time samples**
//! under `pantometry:`, on a prim named after the domain. usdview shows them in its property panel
//! and scrubs them with the timeline.
//!
//! `ARCHITECTURE.md` is right that there is no USD *schema* for a `Ledger` or a `Violation`, and
//! this does not invent one: a custom attribute is a number with a name, which is what a reading
//! is, and nothing here claims a consumer will understand what it means.
//!
//! # Text, and no dependency
//!
//! `.usda` is USD's text serialisation and this writes it by hand, for the same reason glTF and SVG
//! are written by hand here: `pantometry-view` has exactly one dependency and it is
//! `pantometry-scene`. Linking OpenUSD would be a C++ build, a hundred megabytes and a platform
//! matrix, to emit a format that is documented and printable.
//!
//! A `.usda` is what `usdcat` converts to `.usdc` in one command if a pipeline wants the binary
//! crate, so nothing is lost by writing the readable one.
//!
//! # Units and the up axis
//!
//! `metersPerUnit = 1` and `upAxis = "Y"`. Both are stated rather than defaulted: USD's fallback
//! for `metersPerUnit` is **centimetres**, so a file that leaves it out has every part it contains
//! read a hundred times too small, and Y is the axis this workspace's camera treats as up —
//! `viewer_core::Camera` rotates elevation about it and the glTF export writes positions in the
//! same frame.

use crate::mesh::{self, Surface};
use crate::ramp;
use pantometry_scene::{Frame, PanelData};

/// A run as USD, and what the writer left out or decided.
pub struct Staged {
    /// The document. Write it to a `.usda` file.
    pub document: String,
    /// Panels that produced no geometry, and why.
    pub skipped: Vec<String>,
    /// Choices this export made that a reader should know about.
    pub notes: Vec<String>,
}

/// How many frames a second the timeline runs at.
///
/// USD's time codes are unitless and `timeCodesPerSecond` is what turns them into seconds. A run
/// here spans anything from nanoseconds to hours, so the frames are numbered 0, 1, 2 and the
/// **real** time of each is written as an attribute — `pantometry:time_s` — rather than pretended
/// to be a wall clock. A timeline that claimed a four-nanosecond run took four seconds would be a
/// lie in the one place a reader cannot check it.
const TIME_CODES_PER_SECOND: f64 = 24.0;

/// Write a run as a USD stage.
pub fn usda(title: &str, frames: &[Frame]) -> Staged {
    usda_with(title, frames, mesh::Surfaces::Boundary)
}

/// The same, choosing which surface a field becomes. See [`mesh::Surfaces`].
///
/// Separate rather than an extra argument on [`usda`], because that one is published and the
/// files it writes are the ones every caller here already expects. A default nobody asked for is
/// how an export quietly changes shape between versions.
pub fn usda_with(title: &str, frames: &[Frame], surfaces: mesh::Surfaces) -> Staged {
    let mut out = String::with_capacity(1 << 16);
    let mut skipped = Vec::new();
    let mut notes = Vec::new();

    let last = frames.len().saturating_sub(1);
    out.push_str("#usda 1.0\n(\n");
    out.push_str(&format!("    doc = {}\n", quote(title)));
    out.push_str(&format!(
        "    \"\"\"generated by pantometry-view {}\"\"\"\n",
        env!("CARGO_PKG_VERSION")
    ));
    out.push_str("    defaultPrim = \"World\"\n");
    out.push_str("    metersPerUnit = 1\n");
    out.push_str("    upAxis = \"Y\"\n");
    out.push_str(&format!(
        "    timeCodesPerSecond = {TIME_CODES_PER_SECOND}\n"
    ));
    out.push_str("    startTimeCode = 0\n");
    out.push_str(&format!("    endTimeCode = {last}\n"));
    out.push_str(")\n\n");

    out.push_str("def Xform \"World\"\n{\n");
    // The run's own clock, as an attribute rather than as the timeline. See
    // `TIME_CODES_PER_SECOND`.
    if !frames.is_empty() {
        out.push_str("    double pantometry:time_s.timeSamples = {\n");
        for (i, f) in frames.iter().enumerate() {
            out.push_str(&format!("        {i}: {},\n", num(f.time_s)));
        }
        out.push_str("    }\n");
        out.push_str(&format!(
            "    double pantometry:duration_s = {}\n",
            num(frames.last().map_or(0.0, |f| f.time_s))
        ));
        out.push_str(&format!("    int pantometry:frames = {}\n\n", frames.len()));
    }

    let Some(first) = frames.first() else {
        out.push_str("}\n");
        skipped.push("the run produced no frames, so the stage has no geometry".into());
        return Staged {
            document: out,
            skipped,
            notes,
        };
    };

    let mut coloured = false;
    for (pi, panel) in first.panels.iter().enumerate() {
        // Every frame's version of this panel, matched by name rather than by index: a run that
        // gained or lost a domain mid-stream would otherwise animate one thing with another's
        // values.
        let series: Vec<&PanelData> = frames
            .iter()
            .filter_map(|f| f.panels.iter().find(|p| p.name == panel.name))
            .map(|p| &p.data)
            .collect();
        // One scale across the whole run, never per frame, for the reason every other view here
        // states: a frame normalised to itself makes a decay look like a steady state.
        let (lo, hi, signed) = run_span(&series);

        let path = format!("/World/{}", ident(&panel.name));
        match &panel.data {
            PanelData::Field {
                nx,
                ny,
                nz,
                extent_m,
                values,
            } => {
                if [*nx, *ny, *nz].iter().filter(|&&n| n > 1).count() < 2 {
                    skipped.push(format!(
                        "{} is a {nx}x{ny}x{nz} field: a row of samples along a line is a graph, \
                         not geometry",
                        panel.name
                    ));
                    continue;
                }
                if !mesh::presence_is_constant(&series) {
                    notes.push(format!(
                        "{}: which cells hold a value changes during the run, so the geometry is \
                         **frame 0's** and the colours are each frame's. USD animates an \
                         attribute, not a topology, and a points array that changes length \
                         between samples is a file most readers mishandle",
                        panel.name
                    ));
                }
                let surface = surfaces.of((*nx, *ny, *nz), *extent_m, values);
                if surface.indices.is_empty() {
                    // **Two different silences, and they used to share one sentence.** An empty
                    // boundary means no cell holds a value. An empty *level* means the field is
                    // full of values and none of them is the one asked for, which is a number a
                    // person can correct -- so it says what the field actually spans.
                    skipped.push(match surfaces {
                        mesh::Surfaces::Boundary => format!(
                            "{} is a {nx}x{ny}x{nz} field with no cell that holds a value, so it has no surface",
                            panel.name
                        ),
                        mesh::Surfaces::At(level) => {
                            let (lo, hi, _) = mesh::span(values);
                            format!(
                                "{} never reaches {level}: the field spans {lo} to {hi}, so there is no surface at that level",
                                panel.name
                            )
                        }
                    });
                    continue;
                }
                if surface.stride > 1 {
                    notes.push(format!(
                        "{}: subsampled every {} cells — the full surface is over {} faces",
                        panel.name,
                        surface.stride,
                        mesh::MAX_FACES
                    ));
                }
                coloured = true;
                write_mesh(
                    &mut out,
                    &path,
                    &panel.name,
                    panel.unit,
                    &surface,
                    &series,
                    lo,
                    hi,
                    signed,
                    Sampler::Field,
                );
            }
            PanelData::Points {
                positions,
                values,
                bounds,
                ..
            } => {
                let radius = mesh::body_radius(positions, bounds);
                notes.push(format!(
                    "{}: bodies drawn as spheres of radius {radius:.6} m — a size this run does \
                     **not** carry. A body set records positions and a value, not an extent, so \
                     the radius is a quarter of the median distance to the nearest neighbour: a \
                     drawing convention, not a measurement",
                    panel.name
                ));
                // Bodies move, so this is the one place topology alone is not enough — the
                // positions are animated too, which USD does and glTF does not.
                let surface = mesh::body_spheres(positions, radius);
                if surface.indices.is_empty() {
                    skipped.push(format!("{} holds no bodies", panel.name));
                    continue;
                }
                coloured = true;
                write_mesh(
                    &mut out,
                    &path,
                    &panel.name,
                    panel.unit,
                    &surface,
                    &series,
                    lo,
                    hi,
                    signed,
                    Sampler::Bodies { radius },
                );
                let _ = values;
            }
            PanelData::Paths {
                vertices,
                starts,
                values,
                ..
            } => {
                coloured = true;
                write_curves(
                    &mut out,
                    &path,
                    &panel.name,
                    panel.unit,
                    vertices,
                    starts,
                    values,
                    lo,
                    hi,
                    signed,
                );
            }
        }
        let _ = pi;
    }

    // The domains with no shape at all, which is most of a scene here. Grouped under one prim so a
    // hierarchy that is mostly numbers does not bury the geometry.
    write_readings(&mut out, frames);

    out.push_str("}\n");

    if coloured {
        notes.push(
            "colour is `primvars:displayColor`, on one scale across the whole run — so a frame is \
             comparable with every other frame, which is the property a per-frame scale destroys"
                .to_string(),
        );
    }
    Staged {
        document: out,
        skipped,
        notes,
    }
}

/// Which shape a mesh's animated attribute is.
enum Sampler {
    /// A field: the cells do not move, so only the colour is sampled over time.
    Field,
    /// Bodies: they move, so the points are sampled too.
    Bodies { radius: f64 },
}

/// The value range of a panel **across every frame**.
fn run_span(series: &[&PanelData]) -> (f64, f64, bool) {
    let mut lo = f64::MAX;
    let mut hi = f64::MIN;
    for data in series {
        let values = match data {
            PanelData::Field { values, .. }
            | PanelData::Points { values, .. }
            | PanelData::Paths { values, .. } => values,
        };
        for v in values {
            if !v.is_finite() {
                continue;
            }
            lo = lo.min(*v);
            hi = hi.max(*v);
        }
    }
    if !(lo.is_finite() && hi.is_finite()) {
        return (0.0, 1.0, false);
    }
    if hi > lo {
        (lo, hi, ramp::is_signed(lo, hi))
    } else {
        (lo, lo + 1.0, false)
    }
}

/// The values a panel holds in one frame, whichever shape it is.
fn values_of(data: &PanelData) -> &[f64] {
    match data {
        PanelData::Field { values, .. }
        | PanelData::Points { values, .. }
        | PanelData::Paths { values, .. } => values,
    }
}

#[allow(clippy::too_many_arguments)]
fn write_mesh(
    out: &mut String,
    path: &str,
    name: &str,
    unit: &str,
    surface: &Surface,
    series: &[&PanelData],
    lo: f64,
    hi: f64,
    signed: bool,
    sampler: Sampler,
) {
    let b = surface.bounds();
    out.push_str(&format!(
        "    def Mesh \"{}\"\n    {{\n",
        path.rsplit('/').next().unwrap_or("mesh")
    ));
    out.push_str(&format!(
        "        float3[] extent = [({}, {}, {}), ({}, {}, {})]\n",
        b[0], b[1], b[2], b[3], b[4], b[5]
    ));
    // `none`, because these are the faces the simulation has. A subdivision surface would round
    // off a voxel boundary the physics computed as square.
    out.push_str("        uniform token subdivisionScheme = \"none\"\n");
    out.push_str("        int[] faceVertexCounts = [");
    for i in 0..surface.faces() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push('3');
    }
    out.push_str("]\n");
    out.push_str("        int[] faceVertexIndices = [");
    for (i, x) in surface.indices.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&x.to_string());
    }
    out.push_str("]\n");

    match sampler {
        Sampler::Field => {
            out.push_str("        point3f[] points = [");
            write_points(out, &surface.positions);
            out.push_str("]\n");
        }
        Sampler::Bodies { radius } => {
            // Bodies move. The topology is one sphere per body and stays put; the positions are
            // rebuilt each frame from that frame's centres.
            out.push_str("        point3f[] points.timeSamples = {\n");
            for (t, data) in series.iter().enumerate() {
                let PanelData::Points { positions, .. } = data else {
                    continue;
                };
                let s = mesh::body_spheres(positions, radius);
                out.push_str(&format!("            {t}: ["));
                write_points(out, &s.positions);
                out.push_str("],\n");
            }
            out.push_str("        }\n");
        }
    }

    out.push_str("        normal3f[] normals = [");
    write_points(out, &surface.normals);
    out.push_str("]\n");
    out.push_str("        uniform token[] xformOpOrder = []\n");

    // Colour, per vertex, per frame. `displayColor` is what usdview and every USD renderer draw
    // without a material graph, and `interpolation = "vertex"` is what makes it per-vertex rather
    // than one colour for the prim.
    // **Interpolation is attribute metadata, in parentheses.** It was written as a separate
    // property, `primvars:displayColor:interpolation`, which is the spelling for a primvar's
    // `:indices` and is not where USD looks for this. With it missing the attribute falls back to
    // `constant`, so a file carrying a colour per vertex was drawn with the **first one** over the
    // whole prim. Caught by rendering it: scene 23's hot part and cooled lid came out one colour
    // while the file plainly held two, and nothing structural could have said so.
    out.push_str("        color3f[] primvars:displayColor (\n");
    out.push_str("            interpolation = \"vertex\"\n");
    out.push_str("        )\n");
    out.push_str("        color3f[] primvars:displayColor.timeSamples = {\n");
    for (t, data) in series.iter().enumerate() {
        let values = values_of(data);
        out.push_str(&format!("            {t}: ["));
        for (i, src) in surface.source.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            let v = values.get(*src as usize).copied().unwrap_or(f64::NAN);
            let c = linear(v, lo, hi, signed);
            out.push_str(&format!("({}, {}, {})", c[0], c[1], c[2]));
        }
        out.push_str("],\n");
    }
    out.push_str("        }\n");
    out.push_str(&format!(
        "        uniform string pantometry:unit = {}\n",
        quote(unit)
    ));
    out.push_str(&format!(
        "        uniform string pantometry:domain = {}\n",
        quote(name)
    ));
    out.push_str(&format!(
        "        uniform double2 pantometry:range = ({}, {})\n",
        num(lo),
        num(hi)
    ));
    out.push_str("    }\n\n");
}

/// Paths as `BasisCurves`, which is USD's shape for a traced ray or a trajectory.
#[allow(clippy::too_many_arguments)]
fn write_curves(
    out: &mut String,
    path: &str,
    name: &str,
    unit: &str,
    vertices: &[[f64; 3]],
    starts: &[usize],
    values: &[f64],
    lo: f64,
    hi: f64,
    signed: bool,
) {
    out.push_str(&format!(
        "    def BasisCurves \"{}\"\n    {{\n",
        path.rsplit('/').next().unwrap_or("curves")
    ));
    out.push_str("        uniform token type = \"linear\"\n");
    out.push_str("        uniform token wrap = \"nonperiodic\"\n");
    out.push_str("        int[] curveVertexCounts = [");
    for (k, start) in starts.iter().enumerate() {
        let to = starts.get(k + 1).copied().unwrap_or(vertices.len());
        if k > 0 {
            out.push_str(", ");
        }
        out.push_str(&(to - start).to_string());
    }
    out.push_str("]\n");
    out.push_str("        point3f[] points = [");
    for (i, v) in vertices.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!(
            "({}, {}, {})",
            v[0] as f32, v[1] as f32, v[2] as f32
        ));
    }
    out.push_str("]\n");
    // A width no ray carries, and said so. A traced ray is a line; USD draws a curve with a
    // thickness, and one has to be chosen for it to be visible at all.
    let extent = vertices.iter().fold(0.0f64, |m, v| {
        m.max(v[0].abs()).max(v[1].abs()).max(v[2].abs())
    });
    let width = (extent * 2e-3).max(f64::MIN_POSITIVE);
    out.push_str("        float[] widths (\n");
    out.push_str("            interpolation = \"constant\"\n");
    out.push_str("        )\n");
    out.push_str(&format!("        float[] widths = [{}]\n", width as f32));
    // One colour per curve, which is what `uniform` interpolation means on a curve set.
    out.push_str("        color3f[] primvars:displayColor (\n");
    out.push_str("            interpolation = \"uniform\"\n");
    out.push_str("        )\n");
    out.push_str("        color3f[] primvars:displayColor = [");
    for (k, _) in starts.iter().enumerate() {
        if k > 0 {
            out.push_str(", ");
        }
        let c = linear(values.get(k).copied().unwrap_or(lo), lo, hi, signed);
        out.push_str(&format!("({}, {}, {})", c[0], c[1], c[2]));
    }
    out.push_str("]\n");
    out.push_str(&format!(
        "        uniform string pantometry:unit = {}\n",
        quote(unit)
    ));
    out.push_str(&format!(
        "        uniform string pantometry:domain = {}\n",
        quote(name)
    ));
    out.push_str("    }\n\n");
}

/// Every domain's scalars, as custom attributes with time samples.
///
/// This is the half of a scene no picture reaches. Twelve of the twenty-nine shipped scenes have a
/// domain with no field and no bodies, and for several of them the scalar *is* the result — a
/// winding whose resistance follows its own temperature draws nothing at all and is the whole
/// subject of its scene.
fn write_readings(out: &mut String, frames: &[Frame]) {
    let Some(first) = frames.first() else { return };
    if first.readings.is_empty() {
        return;
    }
    let mut domains: Vec<&str> = Vec::new();
    for r in &first.readings {
        if !domains.contains(&r.domain.as_str()) {
            domains.push(&r.domain);
        }
    }
    out.push_str("    def Scope \"Readings\"\n    {\n");
    for domain in domains {
        out.push_str(&format!(
            "        def Scope \"{}\"\n        {{\n",
            ident(domain)
        ));
        let labels: Vec<(&str, &'static str)> = first
            .readings
            .iter()
            .filter(|r| r.domain == domain)
            .map(|r| (r.label.as_str(), r.unit))
            .collect();
        for (label, unit) in labels {
            out.push_str(&format!(
                "            double pantometry:{}.timeSamples = {{\n",
                ident(label)
            ));
            for (t, f) in frames.iter().enumerate() {
                // Matched by name, not by index: a reading missing from a later frame must not
                // take the value of whatever sits in its slot.
                let Some(r) = f
                    .readings
                    .iter()
                    .find(|q| q.domain == domain && q.label == label)
                else {
                    continue;
                };
                if !r.value.is_finite() {
                    // A hole is not a value. USD interpolates between the samples it has, which is
                    // a straight line across the gap — and a straight line is a better answer than
                    // a zero, which is what writing one would mean.
                    continue;
                }
                out.push_str(&format!("                {t}: {},\n", num(r.value)));
            }
            out.push_str("            }\n");
            out.push_str(&format!(
                "            uniform string pantometry:{}:unit = {}\n",
                ident(label),
                quote(unit)
            ));
        }
        out.push_str("        }\n\n");
    }
    out.push_str("    }\n\n");
}

fn write_points(out: &mut String, points: &[[f32; 3]]) {
    for (i, p) in points.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("({}, {}, {})", p[0], p[1], p[2]));
    }
}

/// A colour in **linear** space, which is what `displayColor` is.
///
/// The same trap glTF's `COLOR_0` set: USD's `displayColor` is linear, and writing sRGB bytes over
/// 255 into it hands a renderer a value about 2.3x too bright in the midtones. That defect shipped
/// in the glTF exporter for as long as it existed, and this is the second format to want the same
/// conversion, which is why it is written down twice rather than remembered once.
fn linear(v: f64, lo: f64, hi: f64, signed: bool) -> [f32; 3] {
    let t = mesh::place(v, lo, hi, signed);
    let rgb = if signed {
        ramp::diverging(t)
    } else {
        ramp::sequential(t)
    };
    let to_linear = |b: u8| {
        let c = b as f64 / 255.0;
        let out = if c <= 0.040_45 {
            c / 12.92
        } else {
            ((c + 0.055) / 1.055).powf(2.4)
        };
        out as f32
    };
    [to_linear(rgb[0]), to_linear(rgb[1]), to_linear(rgb[2])]
}

/// A number, at six significant figures, in a spelling USD's parser takes.
///
/// `1e-10` is fine; `NaN` and `inf` are not, and neither is a bare `.5`.
fn num(x: f64) -> String {
    if !x.is_finite() {
        return "0".to_string();
    }
    if x == 0.0 {
        return "0".to_string();
    }
    format!("{x:.6e}")
}

/// A USD prim or property name from a domain's name.
///
/// USD identifiers are `[A-Za-z_][A-Za-z0-9_]*`, and a scene here can call a domain "mean speed"
/// or "div B". Substituted rather than rejected, because a name that cannot be a prim is not a
/// reason to drop a domain from the file — and the original is kept beside it in
/// `pantometry:domain`, so nothing is lost.
fn ident(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for (i, c) in s.chars().enumerate() {
        let ok = c.is_ascii_alphanumeric() || c == '_';
        if !ok {
            out.push('_');
        } else if i == 0 && c.is_ascii_digit() {
            out.push('_');
            out.push(c);
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        out.push('_');
    }
    out
}

fn quote(s: &str) -> String {
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            c if c.is_control() => out.push(' '),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}
